### ISSUE TITLE
Orthographic camera

### ISSUE THREAD

**Issue by FlokiTV** [lucatronica/picocad-web-viewer#1]
Hi! I really love you job, I'm using your script to implement a "3d" on GDevelop
But my scene is orthographic, and your script has a perspective camera.
You can help me config a Orthographic camera?

https://user-images.githubusercontent.com/11356271/126038580-1ba29248-449f-4a95-a1a5-19d6e2333591.mp4

**Comment by lucatronica** [comment]
Hey! You should just need to change from a perspective matrix `mat4.perspective` to an orthographic matrix `mat4.ortho`.

https://github.com/lucatronica/picocad-web-viewer/blob/9686a7cd65f3927cc43d50915a23eefb08f4571e/src/index.js#L390-L396

**Comment by FlokiTV** [comment]
![image](https://user-images.githubusercontent.com/11356271/126190295-c5771977-f0af-43a8-ab94-961090bada69.png)
I tried this, but dont works weel, you can help me?

**Comment by lucatronica** [comment]
Something like this should work better, though it assumes a square aspect ratio. Adjust `scale` to taste.

```js
let scale = 3;
mat4.ortho(
  mat,
  -scale, scale, -scale, scale,
  0.1, 400,
);
```

**Comment by FlokiTV** [comment]
Thanks! Works... I'm dont have experience with webgl
Thanks for contribute with my work on GDevelop

**Comment by FlokiTV** [comment]
https://codepen.io/FlokiTV/pen/MWmmobq
