### ISSUE TITLE
Transparency issue when using a costume texture.

### ISSUE THREAD

**Issue by BMB46** [lucatronica/picocad-web-viewer#2]
Hello, good evenning, everytime I use the web viewer and place a custom texture upon my model the alpha color stops working and doesnt matter what color I change it too, it doesnt recognize it as transparent, was wondering if there was a reason for this, any help is appreciated.

**Comment by lucatrn** [comment]
Hi, sorry for the slow response! This should be fixed now.

Alpha with custom textures were completely broken, nothing on your end.
